server:
  error:
    include-stracktrace: on_param


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pro?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG


